import { CustomApiProvider, SystemPromptMode, CustomApiConfig } from '../src/services/user-config'
import { PROVIDER_DEFAULTS } from './providers/provider-defaults'

// CustomApiConfig をベースにプリセット型を作成（保存時にユーザが埋める項目は除外）
type PresetFromConfig = Omit<CustomApiConfig, 'apiKey' | 'enabled' | 'webAccess' | 'id'>

const apiPresets = {
  version: '1.0.0',
  description: 'API provider presets configuration',
  settings: {
    enableCompanyPresets: false,
    showPerplexityTemplate: false,
  },
  presets: {
    OpenAI: {
      name: 'OpenAI',
      shortName: 'GPT',
      model: 'gpt-5.5',
      host: 'https://api.openai.com',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'OpenAI.Green',
      thinkingMode: true,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    Anthropic: {
      name: 'Anthropic',
      shortName: 'Claud',
      model: 'claude-sonnet-4-6',
      host: 'https://api.anthropic.com/',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'Claude.Orange',
      thinkingMode: true,
      thinkingBudget: 8000,
      provider: CustomApiProvider.Anthropic,
    },

    Gemini: {
      name: 'Google Gemini',
      shortName: 'G Gemin',
      model: 'gemini-3.1-pro-preview',
      host: 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
      isHostFullPath: true,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'Gemini.Color',
      thinkingMode: true,
      thinkingBudget: 8000,
      provider: CustomApiProvider.GeminiOpenAI,
    },

    DeepSeek: {
      name: 'DeepSeek V4',
      shortName: 'DS V4',
      model: 'deepseek-v4-pro',
      host: 'https://api.deepseek.com/',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'deepseek',
      thinkingMode: true,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    Grok: {
      name: 'Grok 4.20',
      shortName: 'Grok',
      model: 'grok-4.20',
      host: 'https://api.x.ai/v1',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'grok',
      thinkingMode: true,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    DeepInfra: {
      name: 'DI DeepSeek V4',
      shortName: 'DI',
      model: 'deepseek-ai/DeepSeek-V4-Pro',
      host: 'https://api.deepinfra.com/v1/openai/chat/completions',
      isHostFullPath: true,
      temperature: 0.7,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'OpenAI.Blue',
      thinkingMode: true,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    Fireworks: {
      name: 'Fireworks AI',
      shortName: 'Fire',
      model: 'accounts/fireworks/models/qwen3-coder-480b-a35b-instruct',
      host: 'https://api.fireworks.ai/inference/v1',
      isHostFullPath: false,
      temperature: 0.6,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'OpenAI.Red',
      thinkingMode: false,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    GLM: {
      name: 'GLM Coding',
      shortName: 'GLM',
      model: 'glm-4.7',
      host: 'https://open.bigmodel.cn/api/coding/paas/v4',
      isHostFullPath: false,
      temperature: 0.7,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'zhipu',
      thinkingMode: false,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    MiMo: {
      name: 'Xiaomi MiMo',
      shortName: 'MiMo',
      model: 'mimo-v2.5-pro',
      host: 'https://api.xiaomimimo.com/v1',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'xiaomi',
      thinkingMode: true,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    Novita: {
      name: 'Novita AI',
      shortName: 'Novita',
      model: 'deepseek/deepseek-v4-pro',
      host: 'https://api.novita.ai/openai',
      isHostFullPath: false,
      temperature: 0.7,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'novita',
      thinkingMode: false,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

  } satisfies Record<string, PresetFromConfig>,
  companyPresets: {},
}

export default apiPresets
